
FROM debian

RUN apt-get -qq update
RUN apt-get -qy install cpanminus git libjson-xs-perl libxml-libxml-perl libxml-libxslt-perl
RUN git clone https://github.com/brucemiller/LaTeXML
WORKDIR /LaTeXML
RUN ln -s tools/pre-commit .git/hooks
RUN cpanm . --notest
RUN apt-get -qy install texlive-full

RUN mkdir /workdir
WORKDIR /workdir
